repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
      - id: flutter-analyze
        name: flutter analyze
        entry: cmd /c "flutter analyze"
        language: system
        types: [dart]
      - id: flutter-format
        name: flutter format
        entry: cmd /c "dart format ."
        language: system
        types: [dart]
      - id: flutter-test
        name: flutter test
        entry: cmd /c "flutter test"
        language: system
        types: [dart]
        pass_filenames: false
